server:
    port: 8081
spring:
    application:
        name: smart-bi
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/smart-bi?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1111
    redis:
        host: 124.221.54.150
        port: 6379
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 1
                time-between-eviction-runs: 10s
        password: redispass123
    jackson:
        default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
    type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
    level:
        com.snwolf: debug
snwolf:
    prompt: 你是一个数据分析师, 接下来我会给你我的分析目标和原始数据, 请告诉我分析结论, 并且要求给出前端Echarts VS的option配置对象js代码, 合理的将数据进行可视化. 其中不要生成注释
