server:
    port: 8081
spring:
    application:
        name: smart-bi
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/smart-bi?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1111
    redis:
        host: 124.221.54.150
        port: 6379
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 1
                time-between-eviction-runs: 10s
        password: redispass123
        database: 1
    jackson:
        default-property-inclusion: non_null # JSON处理时忽略非空字段
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest
        listener:
            simple:
                retry:
                    enabled: true # 开启消费者失败重试
                    initial-interval: 1000ms # 初识的失败等待时长为1秒
                    multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
                    max-attempts: 2 # 最大重试次数
                    stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false
        virtual-host: /
mybatis-plus:
    type-aliases-package: com.snwolf.bi.domain.entity # 别名扫描包
logging:
    level:
        com.snwolf: debug
snwolf:
    prompt: 你是一个数据分析师, 接下来我会给你我的分析目标和原始数据, 请告诉我分析结论, 并且要求给出前端Echarts VS的option配置对象js代码, 合理的将数据进行可视化. 其中不要生成注释
